# Generated by Django 2.2.12 on 2020-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Black Tea', 'Black Tea'), ('Green Tea', 'Green Tea'), ('White Tea', 'White Tea'), ('Rooibos', 'Rooibos'), ('Mix', 'Mix')], default='Black Tea', max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
