# Generated by Django 2.2.12 on 2020-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200412_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subscriptions',
            field=models.ManyToManyField(to='products.Subscription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Black Tea', 'Black Tea'), ('Green Tea', 'Green Tea'), ('White Tea', 'White Tea'), ('Rooibos', 'Rooibos'), ('Mix', 'Mix'), ('Oolong', 'Oolong')], default='Black Tea', max_length=20),
        ),
    ]
