# Generated by Django 2.2.12 on 2020-04-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200416_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
